version: '2'

services:
  s3:
    image: localstack/localstack
    environment:
     - DEBUG=1
     - SERVICES=s3
     - DEFAULT_REGION=ap-southeast-2
     - DATA_DIR=/tmp/s3/data
    ports:
     - "4566:4566"
     - "4571:4571"
    volumes:
      - s3-data:/tmp/s3

volumes:
  s3-data:
