version: '2'

services:
  api:
    image: jlob0/algae
    build: .
    environment:
        AWS_ACCESS_ENDPOINT: "http://s3:4566"
        DB_HOST: "db"
    ports:
     - "8080:8080"
    volumes:
      - ./dev.env:/app/.env

  s3:
    image: localstack/localstack
    environment:
     - DEBUG=1
     - SERVICES=s3
     - DEFAULT_REGION=ap-southeast-2
     - DATA_DIR=/tmp/s3/data
    ports:
     - "4566:4566"
     - "4571:4571"
    volumes:
      - s3-data:/tmp/s3

  db:
      image: timescale/timescaledb:latest-pg13
      environment:
          POSTGRES_PASSWORD: "123456"
          NO_TS_TUNE: "true"
      volumes:
          - db-data:/var/lib/postgresql/data
      ports:
          - "5432:5432"

volumes:
  s3-data:
  db-data:
